/**
 * Optimizer strategy presets — single source of truth for the Optimizer UI.
 *
 * Each preset.request mirrors OptimizationRequest (camelCase) and is applied
 * onto the component form signals. Runtime-only fields (seasonStart,
 * mustInclude, exclude) are intentionally left to the operator.
 *
 * @see OptimizationRequest in core/models/api.models.ts
 * @see artifacts/profiles/optimizer_profiles.json
 */

import { FormationConfig, OptimizationRequest, StrategyProfile } from '../models/api.models';

/** Semantic UI hints — never sent to the solver. */
export interface OptimizerPresetPolicy {
  risk: number;
  stability: number;
  offensiveBonusBias: number;
  coverage: number;
  substitutionValue: number;
  winProbabilityWeight: number;
  robustness: number;
  rosterDepth: number;
  budgetUtilizationTarget: number;
  benchImportance: number;
  captainSafety: number;
  minStartProbability?: number;
  preferBigTeams?: boolean;
  preferMultiRole?: boolean;
  adaptive?: boolean;
  adaptOn?: string[];
}

/**
 * Partial request applied by a preset. Omits operator-owned fields:
 * seasonStart, mustInclude, exclude.
 */
export type OptimizerPresetRequest = Omit<
  OptimizationRequest,
  'seasonStart' | 'mustInclude' | 'exclude'
>;

export interface OptimizerPreset {
  readonly id: string;
  readonly name: string;
  readonly labelIt: string;
  readonly description: string;
  readonly request: OptimizerPresetRequest;
  readonly policy: OptimizerPresetPolicy;
}

/** Sentinel value for the "no preset" option in the select. */
export const OPTIMIZER_PRESET_NONE = '' as const;

export const OPTIMIZER_PRESETS: readonly OptimizerPreset[] = [
  {
    id: "maximum_expected_points",
    name: "Maximum Expected Points",
    labelIt: "Massimo punteggio atteso",
    description: "Massimizza projected_score/season_value senza penalita di rischio. Pesi uniformi, inflazione standard.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 10,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 12,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.6,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.1,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.35,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.0,
      varBlend: 0.0,
      esvWeight: 0.0,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: [
        "BALANCED",
      ],
      customStrategies: null,
    },
    policy: {
      risk: 0.55,
      stability: 0.4,
      offensiveBonusBias: 0.5,
      coverage: 0.45,
      substitutionValue: 0.35,
      winProbabilityWeight: 0.4,
      robustness: 0.35,
      rosterDepth: 0.4,
      budgetUtilizationTarget: 0.95,
      benchImportance: 0.3,
      captainSafety: 0.4,
    },
  },
  {
    id: "maximum_floor",
    name: "Maximum Floor",
    labelIt: "Massimo floor",
    description: "Penalizza alta prediction_std. Preferisce titolari stabili e score prevedibile.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 3,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 10,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.75,
        maxInflationMultiplier: 1.45,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.08,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.25,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-4-2",
        defenders: 4,
        midfielders: 4,
        forwards: 2,
      },
      riskAversion: 1.2,
      varBlend: 0.1,
      esvWeight: 0.05,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: 0.7,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "MAXIMUM_FLOOR",
          roleWeight: {
            P: 1.15,
            D: 1.15,
            C: 1.0,
            A: 0.9,
          },
          minBudgetShareByRoles: [
            [
              "P",
              "D",
            ],
            0.35,
          ],
          maxTopTierPlayers: 4,
          topTierCostThreshold: 28.0,
        },
      ],
    },
    policy: {
      risk: 0.15,
      stability: 0.9,
      offensiveBonusBias: 0.25,
      coverage: 0.7,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.55,
      robustness: 0.85,
      rosterDepth: 0.65,
      budgetUtilizationTarget: 0.88,
      benchImportance: 0.55,
      captainSafety: 0.9,
      minStartProbability: 0.7,
    },
  },
  {
    id: "high_ceiling",
    name: "High Ceiling",
    labelIt: "Alto ceiling",
    description: "Cerca outlier offensivi e season_value. Pesi A/C alti, budget share offensivo.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 8,
      maxPlayersPerTeam: 5,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 14,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.6,
        maxInflationMultiplier: 1.9,
        baseInflationRate: 0.07,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.25,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.4,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "3-4-3",
        defenders: 3,
        midfielders: 4,
        forwards: 3,
      },
      riskAversion: 0.0,
      varBlend: 0.25,
      esvWeight: 0.15,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "HIGH_CEILING",
          roleWeight: {
            P: 0.75,
            D: 0.85,
            C: 1.2,
            A: 1.4,
          },
          minBudgetShareByRoles: [
            [
              "C",
              "A",
            ],
            0.7,
          ],
          maxTopTierPlayers: null,
          topTierCostThreshold: null,
        },
      ],
    },
    policy: {
      risk: 0.85,
      stability: 0.25,
      offensiveBonusBias: 0.95,
      coverage: 0.3,
      substitutionValue: 0.4,
      winProbabilityWeight: 0.35,
      robustness: 0.25,
      rosterDepth: 0.35,
      budgetUtilizationTarget: 0.98,
      benchImportance: 0.25,
      captainSafety: 0.3,
    },
  },
  {
    id: "anti_injury",
    name: "Anti Injury",
    labelIt: "Anti-infortunio",
    description: "Massima profondita e start_probability; diversificazione team; evita over-concentration.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 8,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.75,
        maxInflationMultiplier: 1.4,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.05,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.22,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 1.0,
      varBlend: 0.05,
      esvWeight: 0.1,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: 0.6,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "ANTI_INJURY",
          roleWeight: {
            P: 1.1,
            D: 1.1,
            C: 1.0,
            A: 0.95,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 3,
          topTierCostThreshold: 25.0,
        },
      ],
    },
    policy: {
      risk: 0.2,
      stability: 0.85,
      offensiveBonusBias: 0.3,
      coverage: 0.9,
      substitutionValue: 0.85,
      winProbabilityWeight: 0.5,
      robustness: 0.95,
      rosterDepth: 0.95,
      budgetUtilizationTarget: 0.9,
      benchImportance: 0.9,
      captainSafety: 0.8,
      minStartProbability: 0.6,
    },
  },
  {
    id: "tournament",
    name: "Tournament",
    labelIt: "Torneo / playoff",
    description: "Bilancia ceiling e floor per fasi a eliminazione; budget quasi interamente speso.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 11,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.68,
        maxInflationMultiplier: 1.65,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.15,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.4,
      varBlend: 0.2,
      esvWeight: 0.1,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "TOURNAMENT",
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.05,
            A: 1.15,
          },
          minBudgetShareByRoles: [
            [
              "C",
              "A",
            ],
            0.55,
          ],
          maxTopTierPlayers: 5,
          topTierCostThreshold: 30.0,
        },
      ],
    },
    policy: {
      risk: 0.5,
      stability: 0.55,
      offensiveBonusBias: 0.65,
      coverage: 0.55,
      substitutionValue: 0.5,
      winProbabilityWeight: 0.75,
      robustness: 0.55,
      rosterDepth: 0.5,
      budgetUtilizationTarget: 0.97,
      benchImportance: 0.45,
      captainSafety: 0.55,
    },
  },
  {
    id: "head_to_head",
    name: "Head to Head",
    labelIt: "Testa a testa",
    description: "Score stabile e coperture per scontri diretti; risk aversion medio-alto.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 13,
      maxPlayersPerTeam: 3,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 9,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.72,
        maxInflationMultiplier: 1.5,
        baseInflationRate: 0.045,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.1,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.28,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-4-2",
        defenders: 4,
        midfielders: 4,
        forwards: 2,
      },
      riskAversion: 0.8,
      varBlend: 0.15,
      esvWeight: 0.05,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "HEAD_TO_HEAD",
          roleWeight: {
            P: 1.1,
            D: 1.15,
            C: 1.05,
            A: 0.95,
          },
          minBudgetShareByRoles: [
            [
              "P",
              "D",
            ],
            0.38,
          ],
          maxTopTierPlayers: 4,
          topTierCostThreshold: 28.0,
        },
      ],
    },
    policy: {
      risk: 0.3,
      stability: 0.8,
      offensiveBonusBias: 0.4,
      coverage: 0.75,
      substitutionValue: 0.6,
      winProbabilityWeight: 0.85,
      robustness: 0.8,
      rosterDepth: 0.7,
      budgetUtilizationTarget: 0.92,
      benchImportance: 0.6,
      captainSafety: 0.75,
    },
  },
  {
    id: "balanced_xi",
    name: "Balanced XI",
    labelIt: "XI bilanciato",
    description: "Equilibrio classico allineato alla strategia BALANCED di default del solver.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 10,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.6,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.1,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.25,
      varBlend: 0.1,
      esvWeight: 0.1,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: [
        "BALANCED",
      ],
      customStrategies: null,
    },
    policy: {
      risk: 0.45,
      stability: 0.55,
      offensiveBonusBias: 0.5,
      coverage: 0.55,
      substitutionValue: 0.5,
      winProbabilityWeight: 0.5,
      robustness: 0.55,
      rosterDepth: 0.55,
      budgetUtilizationTarget: 0.93,
      benchImportance: 0.5,
      captainSafety: 0.55,
    },
  },
  {
    id: "rotation_friendly",
    name: "Rotation Friendly",
    labelIt: "Rotation friendly",
    description: "Rosa profonda e intercambiabile; riduce max_per_team; aumenta importanza panchina.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 9,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.72,
        maxInflationMultiplier: 1.5,
        baseInflationRate: 0.045,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.08,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.24,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.6,
      varBlend: 0.1,
      esvWeight: 0.15,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "ROTATION_FRIENDLY",
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.05,
            A: 1.0,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 4,
          topTierCostThreshold: 27.0,
        },
      ],
    },
    policy: {
      risk: 0.35,
      stability: 0.7,
      offensiveBonusBias: 0.4,
      coverage: 0.85,
      substitutionValue: 0.9,
      winProbabilityWeight: 0.45,
      robustness: 0.8,
      rosterDepth: 0.9,
      budgetUtilizationTarget: 0.9,
      benchImportance: 0.95,
      captainSafety: 0.6,
    },
  },
  {
    id: "big_match",
    name: "Big Match",
    labelIt: "Big match",
    description: "Punta su giocatori di big team e moduli offensivi; team strength inflation alta.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 8,
      maxPlayersPerTeam: 5,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 15,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.55,
        maxInflationMultiplier: 1.95,
        baseInflationRate: 0.08,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.4,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.38,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "3-4-3",
        defenders: 3,
        midfielders: 4,
        forwards: 3,
      },
      riskAversion: 0.15,
      varBlend: 0.15,
      esvWeight: 0.05,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "BIG_MATCH",
          roleWeight: {
            P: 0.8,
            D: 0.9,
            C: 1.15,
            A: 1.35,
          },
          minBudgetShareByRoles: [
            [
              "C",
              "A",
            ],
            0.65,
          ],
          maxTopTierPlayers: null,
          topTierCostThreshold: null,
        },
      ],
    },
    policy: {
      risk: 0.7,
      stability: 0.35,
      offensiveBonusBias: 0.85,
      coverage: 0.35,
      substitutionValue: 0.35,
      winProbabilityWeight: 0.6,
      robustness: 0.3,
      rosterDepth: 0.3,
      budgetUtilizationTarget: 0.98,
      benchImportance: 0.25,
      captainSafety: 0.45,
      preferBigTeams: true,
    },
  },
  {
    id: "underdog",
    name: "Underdog",
    labelIt: "Underdog",
    description: "Value fuori dalle big: ESV alto, team_strength disattivato, cap big_teams stretto.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 13,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 6,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        },
    {
          label: "5-4-1",
          defenders: 5,
          midfielders: 4,
          forwards: 1,
        },
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.8,
        maxInflationMultiplier: 1.35,
        baseInflationRate: 0.03,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.0,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.22,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.35,
      varBlend: 0.4,
      esvWeight: 0.5,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "UNDERDOG",
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.05,
            A: 1.05,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 2,
          topTierCostThreshold: 22.0,
        },
      ],
    },
    policy: {
      risk: 0.55,
      stability: 0.45,
      offensiveBonusBias: 0.45,
      coverage: 0.6,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.4,
      robustness: 0.5,
      rosterDepth: 0.6,
      budgetUtilizationTarget: 0.85,
      benchImportance: 0.55,
      captainSafety: 0.4,
      preferBigTeams: false,
    },
  },
  {
    id: "risk_neutral",
    name: "Risk Neutral",
    labelIt: "Risk neutral",
    description: "Obiettivo puro senza risk aversion ne blend VAR/ESV. Comportamento legacy del solver.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 10,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.6,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.0,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.0,
      varBlend: 0.0,
      esvWeight: 0.0,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: [
        "BALANCED",
      ],
      customStrategies: null,
    },
    policy: {
      risk: 0.5,
      stability: 0.5,
      offensiveBonusBias: 0.5,
      coverage: 0.5,
      substitutionValue: 0.5,
      winProbabilityWeight: 0.5,
      robustness: 0.5,
      rosterDepth: 0.5,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.45,
      captainSafety: 0.5,
    },
  },
  {
    id: "safe_captain",
    name: "Safe Captain",
    labelIt: "Capitano sicuro",
    description: "Core affidabile per il capitano: floor alto, bias su A di qualita.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 11,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.68,
        maxInflationMultiplier: 1.55,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.18,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.32,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.9,
      varBlend: 0.05,
      esvWeight: 0.05,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: 0.75,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "SAFE_CAPTAIN",
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.0,
            A: 1.15,
          },
          minBudgetShareByRoles: [
            [
              "A",
            ],
            0.28,
          ],
          maxTopTierPlayers: 5,
          topTierCostThreshold: 30.0,
        },
      ],
    },
    policy: {
      risk: 0.25,
      stability: 0.85,
      offensiveBonusBias: 0.55,
      coverage: 0.6,
      substitutionValue: 0.5,
      winProbabilityWeight: 0.6,
      robustness: 0.75,
      rosterDepth: 0.55,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.45,
      captainSafety: 0.95,
      minStartProbability: 0.75,
    },
  },
  {
    id: "bench_optimized",
    name: "Bench Optimized",
    labelIt: "Panchina ottimizzata",
    description: "Massimizza valore riserve e profondita; ESV alto; multi-team.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 9,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.75,
        maxInflationMultiplier: 1.45,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.05,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.26,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.5,
      varBlend: 0.2,
      esvWeight: 0.35,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "BENCH_OPTIMIZED",
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.05,
            A: 1.0,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 3,
          topTierCostThreshold: 26.0,
        },
      ],
    },
    policy: {
      risk: 0.4,
      stability: 0.65,
      offensiveBonusBias: 0.4,
      coverage: 0.8,
      substitutionValue: 0.95,
      winProbabilityWeight: 0.45,
      robustness: 0.75,
      rosterDepth: 0.95,
      budgetUtilizationTarget: 0.88,
      benchImportance: 1.0,
      captainSafety: 0.55,
    },
  },
  {
    id: "ai_adaptive",
    name: "AI Adaptive",
    labelIt: "AI adattiva",
    description: "Profilo meta: blend VAR/ESV, risk moderato, season_value, team strength attivo.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 11,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.65,
        maxInflationMultiplier: 1.75,
        baseInflationRate: 0.06,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.22,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.45,
      varBlend: 0.3,
      esvWeight: 0.25,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "AI_ADAPTIVE",
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.05,
            A: 1.1,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 5,
          topTierCostThreshold: 30.0,
        },
      ],
    },
    policy: {
      risk: 0.5,
      stability: 0.55,
      offensiveBonusBias: 0.55,
      coverage: 0.6,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.55,
      robustness: 0.6,
      rosterDepth: 0.6,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.55,
      captainSafety: 0.55,
      adaptive: true,
      adaptOn: [
        "multiStrategySpread",
        "effectiveCostRatio",
        "formationFeasibility",
      ],
    },
  },
  {
    id: "championship_mode",
    name: "Championship Mode",
    labelIt: "Modalita scudetto",
    description: "Rosa da titolo: difesa solida + attacco di qualita; win probability prioritaria.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 12,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.68,
        maxInflationMultiplier: 1.7,
        baseInflationRate: 0.055,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.2,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.55,
      varBlend: 0.2,
      esvWeight: 0.15,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "CHAMPIONSHIP",
          roleWeight: {
            P: 1.2,
            D: 1.25,
            C: 1.05,
            A: 1.1,
          },
          minBudgetShareByRoles: [
            [
              "P",
              "D",
            ],
            0.4,
          ],
          maxTopTierPlayers: 5,
          topTierCostThreshold: 32.0,
        },
      ],
    },
    policy: {
      risk: 0.35,
      stability: 0.75,
      offensiveBonusBias: 0.55,
      coverage: 0.7,
      substitutionValue: 0.6,
      winProbabilityWeight: 0.9,
      robustness: 0.85,
      rosterDepth: 0.7,
      budgetUtilizationTarget: 0.96,
      benchImportance: 0.55,
      captainSafety: 0.7,
    },
  },
  {
    id: "mantra_flex",
    name: "Mantra Flex",
    labelIt: "Mantra flessibile",
    description: "Ruleset MANTRA con quote default 12 ruoli; valorizza eligible_roles multipli.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 0,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: [
        "Inter",
        "Milan",
        "Juventus",
        "Napoli",
      ],
      bigTeamsCap: 10,
      formations: [
        {
          label: "3-4-3",
          defenders: 3,
          midfielders: 4,
          forwards: 3,
        },
        {
          label: "3-5-2",
          defenders: 3,
          midfielders: 5,
          forwards: 2,
        },
        {
          label: "4-3-3",
          defenders: 4,
          midfielders: 3,
          forwards: 3,
        },
        {
          label: "4-4-2",
          defenders: 4,
          midfielders: 4,
          forwards: 2,
        },
        {
          label: "4-5-1",
          defenders: 4,
          midfielders: 5,
          forwards: 1,
        },
        {
          label: "5-3-2",
          defenders: 5,
          midfielders: 3,
          forwards: 2,
        }
      ],
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.6,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.12,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.28,
      ruleset: "MANTRA",
      mantraRoleQuotas: {
        Por: 3,
        Dc: 3,
        B: 2,
        Dd: 2,
        Ds: 1,
        E: 1,
        M: 2,
        C: 5,
        T: 1,
        W: 1,
        A: 2,
        Pc: 2,
      },
      preferredFormation: null,
      riskAversion: 0.35,
      varBlend: 0.25,
      esvWeight: 0.2,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: [
        "BALANCED",
      ],
      customStrategies: null,
    },
    policy: {
      risk: 0.45,
      stability: 0.55,
      offensiveBonusBias: 0.5,
      coverage: 0.8,
      substitutionValue: 0.7,
      winProbabilityWeight: 0.55,
      robustness: 0.65,
      rosterDepth: 0.75,
      budgetUtilizationTarget: 0.93,
      benchImportance: 0.65,
      captainSafety: 0.55,
      preferMultiRole: true,
    },
  },
] as const;

/** O(1) lookup by preset id. */
export const OPTIMIZER_PRESETS_BY_ID: ReadonlyMap<string, OptimizerPreset> =
  new Map(OPTIMIZER_PRESETS.map(p => [p.id, p]));

export function findOptimizerPreset(id: string): OptimizerPreset | undefined {
  return OPTIMIZER_PRESETS_BY_ID.get(id);
}

