/**
 * Optimizer strategy presets — single source of truth for the Optimizer UI.
 *
 * Recalibrated on Quotazioni Fantacalcio **2026/27** (Qt.A, n=497):
 * - Pool: minQtA=0→497, 2→411, 3→378, 4→334, 5→283, 6→231, 8→152
 * - Qt.A=1 ≈17.3% (mostly GK reserves) — pure noise for almost every strategy
 * - mean≈6.54  median=5  p75=8  p90≈14  p95≈17.2  max=35
 * - elite ≥18: 25 names | ultra ≥25: 13 | full-elite 25-man cost ≈562 vs budget 500
 * - minQtA is strategy-congruent: floor/safe raise it (≥5), ceiling/risk keep it low (1–2)
 * - topTierCostThreshold anchored to TOP_TIER_COST in shared-presets
 *   (strict=18 / moderate=22 / open=26); ultra-elite ≥25 is scarce but real
 * - maxSinglePlayerBudgetShare: 0.20 floor ↔ 0.40 ceiling; concentration caps
 *   are load-bearing because full-elite squads remain structurally over budget
 *
 * Design principles (FAANG data-engineering):
 * 1. Every numeric knob is justified by the current listino distribution.
 * 2. No orphan / incomplete configs (inflation always carries teamStrengthMultiplier).
 * 3. Risk profiles are orthogonal: floor ≠ anti-injury ≠ H2H ≠ captain.
 * 4. Mantra presets respect 2026/27 official module catalog.
 * 5. Descriptions stay operator-facing and honest about trade-offs.
 *
 * @see OptimizationRequest in core/models/api.models.ts
 * @see TOP_TIER_COST / QT_A_TIERS in shared-presets.ts
 */
import { OptimizationRequest } from '../models/api.models';
import {
  DEFAULT_BIG_TEAMS,
  DEFAULT_FORMATIONS,
  TOP_TIER_COST,
} from './shared-presets';

/** Semantic UI hints — never sent to the solver. */
export interface OptimizerPresetPolicy {
  risk: number;
  stability: number;
  offensiveBonusBias: number;
  coverage: number;
  substitutionValue: number;
  winProbabilityWeight: number;
  robustness: number;
  rosterDepth: number;
  budgetUtilizationTarget: number;
  benchImportance: number;
  captainSafety: number;
  minStartProbability?: number;
  preferBigTeams?: boolean;
  preferMultiRole?: boolean;
  adaptive?: boolean;
  adaptOn?: string[];
}

/**
 * Partial request applied by a preset. Omits operator-owned fields:
 * seasonStart, mustInclude, exclude.
 */
export type OptimizerPresetRequest = Omit<
  OptimizationRequest,
  'seasonStart' | 'mustInclude' | 'exclude'
>;

export interface OptimizerPreset {
  readonly id: string;
  readonly name: string;
  readonly labelIt: string;
  readonly description: string;
  readonly request: OptimizerPresetRequest;
  readonly policy: OptimizerPresetPolicy;
}

/** Sentinel value for the "no preset" option in the select. */
export const OPTIMIZER_PRESET_NONE = '' as const;

export const OPTIMIZER_PRESETS: readonly OptimizerPreset[] = [
  {
    id: 'maximum_expected_points',
    name: 'Maximum Expected Points',
    labelIt: 'Massimo punteggio atteso',
    description:
      'Massimizza projected_score/season_value senza penalità di rischio. Pool ampio ma senza puro rumore Qt.A=1 (2026/27: ~17% noise).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 10,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 12,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.72,
        maxInflationMultiplier: 1.5,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.1,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.34,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.0,
      varBlend: 0.0,
      esvWeight: 0.0,
      valuationMode: 'SEASON_VALUE',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: ['BALANCED'],
      customStrategies: null,
    },
    policy: {
      risk: 0.55,
      stability: 0.4,
      offensiveBonusBias: 0.5,
      coverage: 0.45,
      substitutionValue: 0.35,
      winProbabilityWeight: 0.4,
      robustness: 0.35,
      rosterDepth: 0.4,
      budgetUtilizationTarget: 0.95,
      benchImportance: 0.3,
      captainSafety: 0.4,
    },
  },
  {
    id: 'maximum_floor',
    name: 'Maximum Floor',
    labelIt: 'Massimo floor',
    description:
      'Penalizza alta prediction_std. Preferisce titolari stabili (Qt.A ≥5 = mediana 2026/27, Pr alta) e score prevedibile. Cap concentrazione stretto.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 5,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.78,
        maxInflationMultiplier: 1.35,
        baseInflationRate: 0.03,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.05,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.22,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '4-4-2',
        defenders: 4,
        midfielders: 4,
        forwards: 2,
      },
      riskAversion: 1.25,
      varBlend: 0.06,
      esvWeight: 0.03,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: 0.72,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'MAXIMUM_FLOOR',
          roleWeight: {
            P: 1.18,
            D: 1.18,
            C: 1.0,
            A: 0.88,
          },
          minBudgetShareByRoles: [['P', 'D'], 0.38],
          maxTopTierPlayers: 4,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.1,
      stability: 0.94,
      offensiveBonusBias: 0.2,
      coverage: 0.75,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.55,
      robustness: 0.9,
      rosterDepth: 0.7,
      budgetUtilizationTarget: 0.88,
      benchImportance: 0.55,
      captainSafety: 0.94,
      minStartProbability: 0.72,
    },
  },
  {
    id: 'high_ceiling',
    name: 'High Ceiling',
    labelIt: 'Alto ceiling',
    description:
      'Cerca outlier offensivi e season_value. Pesi A/C alti. Pool ampio (minQtA=1) per non escludere scommesse ad alto potenziale; p95 2026/27 ≈17.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 1,
      minDistinctTeams: 8,
      maxPlayersPerTeam: 5,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 14,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.58,
        maxInflationMultiplier: 1.75,
        baseInflationRate: 0.07,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.22,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.4,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '3-4-3',
        defenders: 3,
        midfielders: 4,
        forwards: 3,
      },
      riskAversion: 0.0,
      varBlend: 0.3,
      esvWeight: 0.2,
      valuationMode: 'SEASON_VALUE',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'HIGH_CEILING',
          roleWeight: {
            P: 0.72,
            D: 0.82,
            C: 1.22,
            A: 1.42,
          },
          minBudgetShareByRoles: [['C', 'A'], 0.72],
          maxTopTierPlayers: null,
          topTierCostThreshold: TOP_TIER_COST.free,
        },
      ],
    },
    policy: {
      risk: 0.9,
      stability: 0.2,
      offensiveBonusBias: 0.96,
      coverage: 0.25,
      substitutionValue: 0.35,
      winProbabilityWeight: 0.3,
      robustness: 0.2,
      rosterDepth: 0.3,
      budgetUtilizationTarget: 0.98,
      benchImportance: 0.2,
      captainSafety: 0.25,
    },
  },
  {
    id: 'anti_injury',
    name: 'Anti Injury',
    labelIt: 'Anti-infortunio',
    description:
      'Massima profondità e start_probability; diversificazione team; evita over-concentration. Solo giocatori usable+ (Qt.A ≥5, 283 nomi in 2026/27).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 5,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 8,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.78,
        maxInflationMultiplier: 1.32,
        baseInflationRate: 0.03,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.03,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.2,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 1.05,
      varBlend: 0.04,
      esvWeight: 0.12,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: 0.62,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'ANTI_INJURY',
          roleWeight: {
            P: 1.12,
            D: 1.12,
            C: 1.0,
            A: 0.92,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 3,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.15,
      stability: 0.9,
      offensiveBonusBias: 0.25,
      coverage: 0.94,
      substitutionValue: 0.9,
      winProbabilityWeight: 0.5,
      robustness: 0.96,
      rosterDepth: 0.96,
      budgetUtilizationTarget: 0.9,
      benchImportance: 0.94,
      captainSafety: 0.82,
      minStartProbability: 0.62,
    },
  },
  {
    id: 'tournament',
    name: 'Tournament',
    labelIt: 'Torneo / playoff',
    description:
      'Bilancia ceiling e floor per fasi a eliminazione; budget quasi interamente speso. Pool di qualità media (Qt.A ≥3 ≈378 nomi).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 11,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.66,
        maxInflationMultiplier: 1.6,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.14,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '4-3-3',
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.38,
      varBlend: 0.22,
      esvWeight: 0.12,
      valuationMode: 'SEASON_VALUE',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'TOURNAMENT',
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.08,
            A: 1.18,
          },
          minBudgetShareByRoles: [['C', 'A'], 0.58],
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.48,
      stability: 0.55,
      offensiveBonusBias: 0.68,
      coverage: 0.55,
      substitutionValue: 0.5,
      winProbabilityWeight: 0.78,
      robustness: 0.55,
      rosterDepth: 0.5,
      budgetUtilizationTarget: 0.97,
      benchImportance: 0.45,
      captainSafety: 0.55,
    },
  },
  {
    id: 'head_to_head',
    name: 'Head to Head',
    labelIt: 'Testa a testa',
    description:
      'Score stabile e coperture per scontri diretti; risk aversion medio-alto. Solo giocatori affidabili (Qt.A ≥5).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 5,
      minDistinctTeams: 13,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 9,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.76,
        maxInflationMultiplier: 1.4,
        baseInflationRate: 0.035,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.07,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.24,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '4-4-2',
        defenders: 4,
        midfielders: 4,
        forwards: 2,
      },
      riskAversion: 0.88,
      varBlend: 0.1,
      esvWeight: 0.04,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: 0.55,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'HEAD_TO_HEAD',
          roleWeight: {
            P: 1.12,
            D: 1.18,
            C: 1.05,
            A: 0.92,
          },
          minBudgetShareByRoles: [['P', 'D'], 0.4],
          maxTopTierPlayers: 4,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.25,
      stability: 0.85,
      offensiveBonusBias: 0.35,
      coverage: 0.8,
      substitutionValue: 0.62,
      winProbabilityWeight: 0.9,
      robustness: 0.85,
      rosterDepth: 0.75,
      budgetUtilizationTarget: 0.92,
      benchImportance: 0.62,
      captainSafety: 0.8,
      minStartProbability: 0.55,
    },
  },
  {
    id: 'balanced_xi',
    name: 'Balanced XI',
    labelIt: 'XI bilanciato',
    description:
      'Equilibrio classico allineato alla strategia BALANCED di default del solver. Filtro leggero sul rumore (Qt.A ≥3).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.5,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.1,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.28,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '4-3-3',
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.25,
      varBlend: 0.1,
      esvWeight: 0.1,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: ['BALANCED'],
      customStrategies: null,
    },
    policy: {
      risk: 0.45,
      stability: 0.55,
      offensiveBonusBias: 0.5,
      coverage: 0.55,
      substitutionValue: 0.5,
      winProbabilityWeight: 0.5,
      robustness: 0.55,
      rosterDepth: 0.55,
      budgetUtilizationTarget: 0.93,
      benchImportance: 0.5,
      captainSafety: 0.55,
    },
  },
  {
    id: 'rotation_friendly',
    name: 'Rotation Friendly',
    labelIt: 'Rotation friendly',
    description:
      'Rosa profonda e intercambiabile; riduce max_per_team; aumenta importanza panchina. Pool usable- (Qt.A ≥4, 334 nomi).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 4,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 9,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.75,
        maxInflationMultiplier: 1.4,
        baseInflationRate: 0.035,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.05,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.22,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.55,
      varBlend: 0.1,
      esvWeight: 0.16,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'ROTATION_FRIENDLY',
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.05,
            A: 1.0,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 4,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.3,
      stability: 0.75,
      offensiveBonusBias: 0.38,
      coverage: 0.9,
      substitutionValue: 0.94,
      winProbabilityWeight: 0.45,
      robustness: 0.85,
      rosterDepth: 0.94,
      budgetUtilizationTarget: 0.9,
      benchImportance: 0.96,
      captainSafety: 0.6,
    },
  },
  {
    id: 'big_match',
    name: 'Big Match',
    labelIt: 'Big match',
    description:
      'Punta su giocatori di big team (Inter/Milan/Napoli/Como top-4 listino) e moduli offensivi; team strength inflation alta.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 8,
      maxPlayersPerTeam: 5,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 15,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.5,
        maxInflationMultiplier: 1.9,
        baseInflationRate: 0.08,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.38,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.38,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '3-4-3',
        defenders: 3,
        midfielders: 4,
        forwards: 3,
      },
      riskAversion: 0.1,
      varBlend: 0.16,
      esvWeight: 0.06,
      valuationMode: 'SEASON_VALUE',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'BIG_MATCH',
          roleWeight: {
            P: 0.78,
            D: 0.88,
            C: 1.18,
            A: 1.38,
          },
          minBudgetShareByRoles: [['C', 'A'], 0.68],
          maxTopTierPlayers: null,
          topTierCostThreshold: TOP_TIER_COST.free,
        },
      ],
    },
    policy: {
      risk: 0.75,
      stability: 0.3,
      offensiveBonusBias: 0.9,
      coverage: 0.3,
      substitutionValue: 0.3,
      winProbabilityWeight: 0.62,
      robustness: 0.25,
      rosterDepth: 0.25,
      budgetUtilizationTarget: 0.98,
      benchImportance: 0.2,
      captainSafety: 0.4,
      preferBigTeams: true,
    },
  },
  {
    id: 'underdog',
    name: 'Underdog',
    labelIt: 'Underdog',
    description:
      'Value fuori dalle big: ESV alto, team_strength disattivato, cap big_teams stretto. Esclude rumore puro (Qt.A ≥3) ma cerca value mid-tier (p50–p75).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 13,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 5,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.84,
        maxInflationMultiplier: 1.25,
        baseInflationRate: 0.02,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.0,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.2,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.32,
      varBlend: 0.45,
      esvWeight: 0.55,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'UNDERDOG',
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.08,
            A: 1.08,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 2,
          topTierCostThreshold: TOP_TIER_COST.strict,
        },
      ],
    },
    policy: {
      risk: 0.55,
      stability: 0.45,
      offensiveBonusBias: 0.45,
      coverage: 0.62,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.38,
      robustness: 0.5,
      rosterDepth: 0.62,
      budgetUtilizationTarget: 0.85,
      benchImportance: 0.55,
      captainSafety: 0.38,
      preferBigTeams: false,
    },
  },
  {
    id: 'risk_neutral',
    name: 'Risk Neutral',
    labelIt: 'Risk neutral',
    description:
      'Obiettivo puro senza risk aversion né blend VAR/ESV. Comportamento legacy del solver. Filtro minimo sul rumore (Qt.A ≥2).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.5,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.0,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.28,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.0,
      varBlend: 0.0,
      esvWeight: 0.0,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: ['BALANCED'],
      customStrategies: null,
    },
    policy: {
      risk: 0.5,
      stability: 0.5,
      offensiveBonusBias: 0.5,
      coverage: 0.5,
      substitutionValue: 0.5,
      winProbabilityWeight: 0.5,
      robustness: 0.5,
      rosterDepth: 0.5,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.45,
      captainSafety: 0.5,
    },
  },
  {
    id: 'safe_captain',
    name: 'Safe Captain',
    labelIt: 'Capitano sicuro',
    description:
      'Core affidabile per il capitano: floor alto, bias su A di qualità. Solo giocatori solidi (Qt.A ≥6 ≈231 nomi, Pr ≥0.75).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 6,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 11,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.45,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.14,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.32,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '4-3-3',
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 1.0,
      varBlend: 0.03,
      esvWeight: 0.03,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: 0.75,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'SAFE_CAPTAIN',
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.0,
            A: 1.2,
          },
          minBudgetShareByRoles: [['A'], 0.3],
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.2,
      stability: 0.9,
      offensiveBonusBias: 0.58,
      coverage: 0.6,
      substitutionValue: 0.48,
      winProbabilityWeight: 0.62,
      robustness: 0.8,
      rosterDepth: 0.55,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.4,
      captainSafety: 0.97,
      minStartProbability: 0.75,
    },
  },
  {
    id: 'bench_optimized',
    name: 'Bench Optimized',
    labelIt: 'Panchina ottimizzata',
    description:
      'Massimizza valore riserve e profondità; ESV alto; multi-team. Pool usable- senza rumore puro (Qt.A ≥4).',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 4,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 9,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.78,
        maxInflationMultiplier: 1.35,
        baseInflationRate: 0.03,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.03,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.22,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.48,
      varBlend: 0.24,
      esvWeight: 0.4,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'BENCH_OPTIMIZED',
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.05,
            A: 1.0,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 3,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.35,
      stability: 0.7,
      offensiveBonusBias: 0.35,
      coverage: 0.85,
      substitutionValue: 0.97,
      winProbabilityWeight: 0.45,
      robustness: 0.8,
      rosterDepth: 0.97,
      budgetUtilizationTarget: 0.88,
      benchImportance: 1.0,
      captainSafety: 0.55,
    },
  },
  {
    id: 'ai_adaptive',
    name: 'AI Adaptive',
    labelIt: 'AI adattiva',
    description:
      'Profilo meta: blend VAR/ESV, risk moderato, season_value, team strength attivo. Filtro leggero (Qt.A ≥3). Adatta su spread multi-strategy e feasibility.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 11,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.64,
        maxInflationMultiplier: 1.65,
        baseInflationRate: 0.055,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.18,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.42,
      varBlend: 0.32,
      esvWeight: 0.26,
      valuationMode: 'SEASON_VALUE',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'AI_ADAPTIVE',
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.08,
            A: 1.12,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.5,
      stability: 0.55,
      offensiveBonusBias: 0.55,
      coverage: 0.6,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.55,
      robustness: 0.6,
      rosterDepth: 0.6,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.55,
      captainSafety: 0.55,
      adaptive: true,
      adaptOn: [
        'multiStrategySpread',
        'effectiveCostRatio',
        'formationFeasibility',
      ],
    },
  },
  {
    id: 'championship_mode',
    name: 'Championship Mode',
    labelIt: 'Modalità scudetto',
    description:
      'Rosa da titolo: difesa solida + attacco di qualità; win probability prioritaria. Giocatori affidabili (Qt.A ≥4). Inter/Milan bias naturale via team strength.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 4,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 12,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.66,
        maxInflationMultiplier: 1.6,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.16,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.3,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: {
        label: '4-3-3',
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.52,
      varBlend: 0.16,
      esvWeight: 0.12,
      valuationMode: 'SEASON_VALUE',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: [
        {
          name: 'CHAMPIONSHIP',
          roleWeight: {
            P: 1.22,
            D: 1.28,
            C: 1.05,
            A: 1.12,
          },
          minBudgetShareByRoles: [['P', 'D'], 0.42],
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.3,
      stability: 0.8,
      offensiveBonusBias: 0.55,
      coverage: 0.75,
      substitutionValue: 0.6,
      winProbabilityWeight: 0.94,
      robustness: 0.9,
      rosterDepth: 0.75,
      budgetUtilizationTarget: 0.96,
      benchImportance: 0.55,
      captainSafety: 0.75,
    },
  },
  {
    id: 'mantra_flex',
    name: 'Mantra Flex',
    labelIt: 'Mantra flessibile',
    description:
      'Ruleset MANTRA con quote default 12 ruoli; valorizza eligible_roles multipli. Pool ampio (minQtA=2) per massimizzare flessibilità di modulo 2026/27.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.5,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.12,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.28,
      ruleset: 'MANTRA',
      mantraRoleQuotas: {
        Por: 3,
        Dc: 3,
        B: 2,
        Dd: 2,
        Ds: 1,
        E: 1,
        M: 2,
        C: 5,
        T: 1,
        W: 1,
        A: 2,
        Pc: 2,
      },
      preferredFormation: null,
      riskAversion: 0.32,
      varBlend: 0.26,
      esvWeight: 0.2,
      valuationMode: 'SEASON_VALUE',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: ['BALANCED'],
      customStrategies: null,
    },
    policy: {
      risk: 0.45,
      stability: 0.55,
      offensiveBonusBias: 0.5,
      coverage: 0.85,
      substitutionValue: 0.75,
      winProbabilityWeight: 0.55,
      robustness: 0.7,
      rosterDepth: 0.8,
      budgetUtilizationTarget: 0.93,
      benchImportance: 0.7,
      captainSafety: 0.55,
      preferMultiRole: true,
    },
  },
  {
    id: 'robust_monte_carlo',
    name: 'Robust Monte Carlo',
    labelIt: 'Rosa robusta (Monte Carlo)',
    description:
      'SAA a N basso: massimizza stabilità della rosa sotto incertezza ML. riskAversion basso per evitare doppio conteggio con MC. Ideale pre-asta quando prediction_std è disponibile.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 10,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 12,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.72,
        maxInflationMultiplier: 1.35,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.08,
      },
      solverTimeoutSeconds: 45,
      maxSinglePlayerBudgetShare: 0.22,
      ruleset: 'CLASSIC',
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.12,
      varBlend: 0.15,
      esvWeight: 0.1,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: 0.35,
      replacementMethod: 'percentile',
      strategyNames: null,
      customStrategies: null,
      monteCarlo: {
        enabled: true,
        nSimulations: 12,
        mode: 'saa_frequency',
        riskLambda: 0.45,
        randomSeed: 42,
      },
      nearOptimal: {
        enabled: true,
        nAlternatives: 3,
        excludeTopM: 2,
        maxScoreDropPct: 0.12,
      },
    },
    policy: {
      risk: 0.22,
      stability: 0.92,
      offensiveBonusBias: 0.35,
      coverage: 0.78,
      substitutionValue: 0.68,
      winProbabilityWeight: 0.72,
      robustness: 0.94,
      rosterDepth: 0.72,
      budgetUtilizationTarget: 0.92,
      benchImportance: 0.55,
      captainSafety: 0.78,
      minStartProbability: 0.35,
      preferBigTeams: false,
      preferMultiRole: true,
      adaptive: false,
    },
  },
  {
    id: 'mantra_3_4_3_flexible',
    name: 'Mantra 3-4-3 (soft preferred)',
    labelIt: 'Mantra 3-4-3 (preferenza soft)',
    description:
      'Ruleset MANTRA con preferredMantraFormation=3-4-3 in modalità soft (post-hoc coverage). Prefer multi-role. Non impone vincolo hard ILP — usa enforcePreferredMantraFormation solo dopo dogfood.',
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 10,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 12,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.4,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.1,
      },
      solverTimeoutSeconds: 45,
      maxSinglePlayerBudgetShare: 0.28,
      ruleset: 'MANTRA',
      mantraRoleQuotas: null,
      preferredFormation: null,
      preferredMantraFormation: '3-4-3',
      enforcePreferredMantraFormation: false,
      riskAversion: 0.1,
      varBlend: 0.0,
      esvWeight: 0.0,
      valuationMode: 'PER_MATCH_RATING',
      minStartProbability: null,
      replacementMethod: 'percentile',
      strategyNames: ['BALANCED'],
      customStrategies: null,
    },
    policy: {
      risk: 0.35,
      stability: 0.7,
      offensiveBonusBias: 0.55,
      coverage: 0.85,
      substitutionValue: 0.7,
      winProbabilityWeight: 0.55,
      robustness: 0.65,
      rosterDepth: 0.75,
      budgetUtilizationTarget: 0.92,
      benchImportance: 0.6,
      captainSafety: 0.55,
      preferMultiRole: true,
      adaptive: false,
    },
  },
] as const;

/** O(1) lookup by preset id. */
export const OPTIMIZER_PRESETS_BY_ID: ReadonlyMap<string, OptimizerPreset> =
  new Map(OPTIMIZER_PRESETS.map(p => [p.id, p]));

export function findOptimizerPreset(id: string): OptimizerPreset | undefined {
  return OPTIMIZER_PRESETS_BY_ID.get(id);
}
