/**
 * Optimizer strategy presets — single source of truth for the Optimizer UI.
 *
 * Recalibrated on Quotazioni Fantacalcio pooled 2023/24–2025/26 (Qt.A):
 * - Pool sizes 2025/26 (8-team need ~200 slots): minQtA=0→532, 3→~420, 5→~355, 8→~248
 * - Qt.A=1 ≈14% of the list (mostly GK reserves) — pure noise for almost every strategy
 * - minQtA is strategy-congruent: floor/safe raise it (≥5), ceiling/risk keep it low (1–2)
 * - topTierCostThreshold anchored to TOP_TIER_COST in shared-presets
 *   (strict=20 / moderate=24 / open=28); ultra-elite ≥26 is rare (≤10 names in 2025/26)
 * - maxSinglePlayerBudgetShare: 0.24 floor ↔ 0.40 ceiling; full-elite 25-man cost
 *   ≈553–592 vs budget 500 → concentration caps are load-bearing
 *
 * @see OptimizationRequest in core/models/api.models.ts
 * @see TOP_TIER_COST / QT_A_TIERS in shared-presets.ts
 */
import { OptimizationRequest } from '../models/api.models';
import {
  DEFAULT_BIG_TEAMS,
  DEFAULT_FORMATIONS,
  TOP_TIER_COST,
} from './shared-presets';

/** Semantic UI hints — never sent to the solver. */
export interface OptimizerPresetPolicy {
  risk: number;
  stability: number;
  offensiveBonusBias: number;
  coverage: number;
  substitutionValue: number;
  winProbabilityWeight: number;
  robustness: number;
  rosterDepth: number;
  budgetUtilizationTarget: number;
  benchImportance: number;
  captainSafety: number;
  minStartProbability?: number;
  preferBigTeams?: boolean;
  preferMultiRole?: boolean;
  adaptive?: boolean;
  adaptOn?: string[];
}

/**
 * Partial request applied by a preset. Omits operator-owned fields:
 * seasonStart, mustInclude, exclude.
 */
export type OptimizerPresetRequest = Omit<
  OptimizationRequest,
  'seasonStart' | 'mustInclude' | 'exclude'
>;

export interface OptimizerPreset {
  readonly id: string;
  readonly name: string;
  readonly labelIt: string;
  readonly description: string;
  readonly request: OptimizerPresetRequest;
  readonly policy: OptimizerPresetPolicy;
}

/** Sentinel value for the "no preset" option in the select. */
export const OPTIMIZER_PRESET_NONE = '' as const;

export const OPTIMIZER_PRESETS: readonly OptimizerPreset[] = [
  {
    id: "maximum_expected_points",
    name: "Maximum Expected Points",
    labelIt: "Massimo punteggio atteso",
    description:
      "Massimizza projected_score/season_value senza penalità di rischio. Pool ampio ma senza puro rumore Qt.A=1.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 10,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 12,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.70,
        maxInflationMultiplier: 1.55,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.10,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.35,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.0,
      varBlend: 0.0,
      esvWeight: 0.0,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: ["BALANCED"],
      customStrategies: null,
    },
    policy: {
      risk: 0.55,
      stability: 0.40,
      offensiveBonusBias: 0.50,
      coverage: 0.45,
      substitutionValue: 0.35,
      winProbabilityWeight: 0.40,
      robustness: 0.35,
      rosterDepth: 0.40,
      budgetUtilizationTarget: 0.95,
      benchImportance: 0.30,
      captainSafety: 0.40,
    },
  },
  {
    id: "maximum_floor",
    name: "Maximum Floor",
    labelIt: "Massimo floor",
    description:
      "Penalizza alta prediction_std. Preferisce titolari stabili (Qt.A ≥5, Pr alta) e score prevedibile.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 5,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.76,
        maxInflationMultiplier: 1.40,
        baseInflationRate: 0.035,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.06,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.24,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-4-2",
        defenders: 4,
        midfielders: 4,
        forwards: 2,
      },
      riskAversion: 1.2,
      varBlend: 0.08,
      esvWeight: 0.04,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: 0.70,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "MAXIMUM_FLOOR",
          roleWeight: {
            P: 1.15,
            D: 1.15,
            C: 1.0,
            A: 0.90,
          },
          minBudgetShareByRoles: [["P", "D"], 0.36],
          maxTopTierPlayers: 4,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.12,
      stability: 0.92,
      offensiveBonusBias: 0.22,
      coverage: 0.72,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.55,
      robustness: 0.88,
      rosterDepth: 0.68,
      budgetUtilizationTarget: 0.88,
      benchImportance: 0.55,
      captainSafety: 0.92,
      minStartProbability: 0.70,
    },
  },
  {
    id: "high_ceiling",
    name: "High Ceiling",
    labelIt: "Alto ceiling",
    description:
      "Cerca outlier offensivi e season_value. Pesi A/C alti. Pool ampio (minQtA basso) per non escludere scommesse ad alto potenziale.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 1,
      minDistinctTeams: 8,
      maxPlayersPerTeam: 5,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 14,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.60,
        maxInflationMultiplier: 1.80,
        baseInflationRate: 0.07,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.25,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.40,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "3-4-3",
        defenders: 3,
        midfielders: 4,
        forwards: 3,
      },
      riskAversion: 0.0,
      varBlend: 0.28,
      esvWeight: 0.18,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "HIGH_CEILING",
          roleWeight: {
            P: 0.75,
            D: 0.85,
            C: 1.20,
            A: 1.40,
          },
          minBudgetShareByRoles: [["C", "A"], 0.70],
          maxTopTierPlayers: null,
          topTierCostThreshold: TOP_TIER_COST.free,
        },
      ],
    },
    policy: {
      risk: 0.88,
      stability: 0.22,
      offensiveBonusBias: 0.95,
      coverage: 0.28,
      substitutionValue: 0.38,
      winProbabilityWeight: 0.32,
      robustness: 0.22,
      rosterDepth: 0.32,
      budgetUtilizationTarget: 0.98,
      benchImportance: 0.22,
      captainSafety: 0.28,
    },
  },
  {
    id: "anti_injury",
    name: "Anti Injury",
    labelIt: "Anti-infortunio",
    description:
      "Massima profondità e start_probability; diversificazione team; evita over-concentration. Solo giocatori con Qt.A ≥5 (usable+).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 5,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 8,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.76,
        maxInflationMultiplier: 1.38,
        baseInflationRate: 0.035,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.04,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.20,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 1.0,
      varBlend: 0.05,
      esvWeight: 0.10,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: 0.60,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "ANTI_INJURY",
          roleWeight: {
            P: 1.10,
            D: 1.10,
            C: 1.0,
            A: 0.95,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 3,
          topTierCostThreshold: 22,
        },
      ],
    },
    policy: {
      risk: 0.18,
      stability: 0.88,
      offensiveBonusBias: 0.28,
      coverage: 0.92,
      substitutionValue: 0.88,
      winProbabilityWeight: 0.50,
      robustness: 0.95,
      rosterDepth: 0.95,
      budgetUtilizationTarget: 0.90,
      benchImportance: 0.92,
      captainSafety: 0.82,
      minStartProbability: 0.60,
    },
  },
  {
    id: "tournament",
    name: "Tournament",
    labelIt: "Torneo / playoff",
    description:
      "Bilancia ceiling e floor per fasi a eliminazione; budget quasi interamente speso. Pool di qualità media (Qt.A ≥3).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 11,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.66,
        maxInflationMultiplier: 1.65,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.15,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.30,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.40,
      varBlend: 0.20,
      esvWeight: 0.10,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "TOURNAMENT",
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.05,
            A: 1.15,
          },
          minBudgetShareByRoles: [["C", "A"], 0.55],
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.48,
      stability: 0.55,
      offensiveBonusBias: 0.65,
      coverage: 0.55,
      substitutionValue: 0.50,
      winProbabilityWeight: 0.75,
      robustness: 0.55,
      rosterDepth: 0.50,
      budgetUtilizationTarget: 0.97,
      benchImportance: 0.45,
      captainSafety: 0.55,
    },
  },
  {
    id: "head_to_head",
    name: "Head to Head",
    labelIt: "Testa a testa",
    description:
      "Score stabile e coperture per scontri diretti; risk aversion medio-alto. Solo giocatori affidabili (Qt.A ≥5).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 5,
      minDistinctTeams: 13,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 9,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.74,
        maxInflationMultiplier: 1.45,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.08,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.26,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-4-2",
        defenders: 4,
        midfielders: 4,
        forwards: 2,
      },
      riskAversion: 0.85,
      varBlend: 0.12,
      esvWeight: 0.04,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "HEAD_TO_HEAD",
          roleWeight: {
            P: 1.10,
            D: 1.15,
            C: 1.05,
            A: 0.95,
          },
          minBudgetShareByRoles: [["P", "D"], 0.38],
          maxTopTierPlayers: 4,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.28,
      stability: 0.82,
      offensiveBonusBias: 0.38,
      coverage: 0.78,
      substitutionValue: 0.60,
      winProbabilityWeight: 0.88,
      robustness: 0.82,
      rosterDepth: 0.72,
      budgetUtilizationTarget: 0.92,
      benchImportance: 0.60,
      captainSafety: 0.78,
    },
  },
  {
    id: "balanced_xi",
    name: "Balanced XI",
    labelIt: "XI bilanciato",
    description:
      "Equilibrio classico allineato alla strategia BALANCED di default del solver. Filtro leggero sul rumore (Qt.A ≥3).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.70,
        maxInflationMultiplier: 1.55,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.10,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.30,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.25,
      varBlend: 0.10,
      esvWeight: 0.10,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: ["BALANCED"],
      customStrategies: null,
    },
    policy: {
      risk: 0.45,
      stability: 0.55,
      offensiveBonusBias: 0.50,
      coverage: 0.55,
      substitutionValue: 0.50,
      winProbabilityWeight: 0.50,
      robustness: 0.55,
      rosterDepth: 0.55,
      budgetUtilizationTarget: 0.93,
      benchImportance: 0.50,
      captainSafety: 0.55,
    },
  },
  {
    id: "rotation_friendly",
    name: "Rotation Friendly",
    labelIt: "Rotation friendly",
    description:
      "Rosa profonda e intercambiabile; riduce max_per_team; aumenta importanza panchina. Pool usable (Qt.A ≥4).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 4,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 9,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.74,
        maxInflationMultiplier: 1.45,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.06,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.22,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.60,
      varBlend: 0.10,
      esvWeight: 0.15,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "ROTATION_FRIENDLY",
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.05,
            A: 1.0,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 4,
          topTierCostThreshold: TOP_TIER_COST.moderate,
        },
      ],
    },
    policy: {
      risk: 0.32,
      stability: 0.72,
      offensiveBonusBias: 0.38,
      coverage: 0.88,
      substitutionValue: 0.92,
      winProbabilityWeight: 0.45,
      robustness: 0.82,
      rosterDepth: 0.92,
      budgetUtilizationTarget: 0.90,
      benchImportance: 0.95,
      captainSafety: 0.60,
    },
  },
  {
    id: "big_match",
    name: "Big Match",
    labelIt: "Big match",
    description:
      "Punta su giocatori di big team e moduli offensivi; team strength inflation alta. Pool ampio per non escludere talenti delle grandi.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 8,
      maxPlayersPerTeam: 5,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 15,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.52,
        maxInflationMultiplier: 1.95,
        baseInflationRate: 0.08,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.40,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.38,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "3-4-3",
        defenders: 3,
        midfielders: 4,
        forwards: 3,
      },
      riskAversion: 0.12,
      varBlend: 0.15,
      esvWeight: 0.05,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "BIG_MATCH",
          roleWeight: {
            P: 0.80,
            D: 0.90,
            C: 1.15,
            A: 1.35,
          },
          minBudgetShareByRoles: [["C", "A"], 0.65],
          maxTopTierPlayers: null,
          topTierCostThreshold: TOP_TIER_COST.free,
        },
      ],
    },
    policy: {
      risk: 0.72,
      stability: 0.32,
      offensiveBonusBias: 0.88,
      coverage: 0.32,
      substitutionValue: 0.32,
      winProbabilityWeight: 0.60,
      robustness: 0.28,
      rosterDepth: 0.28,
      budgetUtilizationTarget: 0.98,
      benchImportance: 0.22,
      captainSafety: 0.42,
      preferBigTeams: true,
    },
  },
  {
    id: "underdog",
    name: "Underdog",
    labelIt: "Underdog",
    description:
      "Value fuori dalle big: ESV alto, team_strength disattivato, cap big_teams stretto. Esclude rumore puro (Qt.A ≥3) ma cerca value mid-tier.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 13,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 6,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.82,
        maxInflationMultiplier: 1.30,
        baseInflationRate: 0.025,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.0,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.20,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.35,
      varBlend: 0.42,
      esvWeight: 0.52,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "UNDERDOG",
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.05,
            A: 1.05,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 2,
          topTierCostThreshold: TOP_TIER_COST.strict,
        },
      ],
    },
    policy: {
      risk: 0.55,
      stability: 0.45,
      offensiveBonusBias: 0.45,
      coverage: 0.60,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.40,
      robustness: 0.50,
      rosterDepth: 0.60,
      budgetUtilizationTarget: 0.85,
      benchImportance: 0.55,
      captainSafety: 0.40,
      preferBigTeams: false,
    },
  },
  {
    id: "risk_neutral",
    name: "Risk Neutral",
    labelIt: "Risk neutral",
    description:
      "Obiettivo puro senza risk aversion né blend VAR/ESV. Comportamento legacy del solver. Filtro minimo sul rumore.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.70,
        maxInflationMultiplier: 1.55,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.0,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.30,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.0,
      varBlend: 0.0,
      esvWeight: 0.0,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: ["BALANCED"],
      customStrategies: null,
    },
    policy: {
      risk: 0.50,
      stability: 0.50,
      offensiveBonusBias: 0.50,
      coverage: 0.50,
      substitutionValue: 0.50,
      winProbabilityWeight: 0.50,
      robustness: 0.50,
      rosterDepth: 0.50,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.45,
      captainSafety: 0.50,
    },
  },
  {
    id: "safe_captain",
    name: "Safe Captain",
    labelIt: "Capitano sicuro",
    description:
      "Core affidabile per il capitano: floor alto, bias su A di qualità. Solo giocatori solidi (Qt.A ≥6, Pr ≥0.75).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 6,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 11,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.68,
        maxInflationMultiplier: 1.50,
        baseInflationRate: 0.045,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.16,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.32,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.95,
      varBlend: 0.04,
      esvWeight: 0.04,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: 0.75,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "SAFE_CAPTAIN",
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.0,
            A: 1.18,
          },
          minBudgetShareByRoles: [["A"], 0.28],
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.22,
      stability: 0.88,
      offensiveBonusBias: 0.55,
      coverage: 0.60,
      substitutionValue: 0.48,
      winProbabilityWeight: 0.60,
      robustness: 0.78,
      rosterDepth: 0.55,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.42,
      captainSafety: 0.96,
      minStartProbability: 0.75,
    },
  },
  {
    id: "bench_optimized",
    name: "Bench Optimized",
    labelIt: "Panchina ottimizzata",
    description:
      "Massimizza valore riserve e profondità; ESV alto; multi-team. Pool usable senza rumore puro (Qt.A ≥4).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 4,
      minDistinctTeams: 14,
      maxPlayersPerTeam: 3,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 9,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.76,
        maxInflationMultiplier: 1.40,
        baseInflationRate: 0.035,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.04,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.24,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.50,
      varBlend: 0.22,
      esvWeight: 0.38,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "BENCH_OPTIMIZED",
          roleWeight: {
            P: 1.05,
            D: 1.05,
            C: 1.05,
            A: 1.0,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 3,
          topTierCostThreshold: 22,
        },
      ],
    },
    policy: {
      risk: 0.38,
      stability: 0.68,
      offensiveBonusBias: 0.38,
      coverage: 0.82,
      substitutionValue: 0.96,
      winProbabilityWeight: 0.45,
      robustness: 0.78,
      rosterDepth: 0.96,
      budgetUtilizationTarget: 0.88,
      benchImportance: 1.0,
      captainSafety: 0.55,
    },
  },
  {
    id: "ai_adaptive",
    name: "AI Adaptive",
    labelIt: "AI adattiva",
    description:
      "Profilo meta: blend VAR/ESV, risk moderato, season_value, team strength attivo. Filtro leggero (Qt.A ≥3).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 3,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 11,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.64,
        maxInflationMultiplier: 1.70,
        baseInflationRate: 0.06,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.20,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.30,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: null,
      riskAversion: 0.45,
      varBlend: 0.30,
      esvWeight: 0.25,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "AI_ADAPTIVE",
          roleWeight: {
            P: 1.0,
            D: 1.05,
            C: 1.05,
            A: 1.10,
          },
          minBudgetShareByRoles: null,
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.50,
      stability: 0.55,
      offensiveBonusBias: 0.55,
      coverage: 0.60,
      substitutionValue: 0.55,
      winProbabilityWeight: 0.55,
      robustness: 0.60,
      rosterDepth: 0.60,
      budgetUtilizationTarget: 0.94,
      benchImportance: 0.55,
      captainSafety: 0.55,
      adaptive: true,
      adaptOn: [
        "multiStrategySpread",
        "effectiveCostRatio",
        "formationFeasibility",
      ],
    },
  },
  {
    id: "championship_mode",
    name: "Championship Mode",
    labelIt: "Modalità scudetto",
    description:
      "Rosa da titolo: difesa solida + attacco di qualità; win probability prioritaria. Giocatori affidabili (Qt.A ≥4).",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 4,
      minDistinctTeams: 11,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 12,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.66,
        maxInflationMultiplier: 1.65,
        baseInflationRate: 0.055,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.18,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.30,
      ruleset: "CLASSIC",
      mantraRoleQuotas: null,
      preferredFormation: {
        label: "4-3-3",
        defenders: 4,
        midfielders: 3,
        forwards: 3,
      },
      riskAversion: 0.55,
      varBlend: 0.18,
      esvWeight: 0.14,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: null,
      customStrategies: [
        {
          name: "CHAMPIONSHIP",
          roleWeight: {
            P: 1.20,
            D: 1.25,
            C: 1.05,
            A: 1.10,
          },
          minBudgetShareByRoles: [["P", "D"], 0.40],
          maxTopTierPlayers: 5,
          topTierCostThreshold: TOP_TIER_COST.open,
        },
      ],
    },
    policy: {
      risk: 0.32,
      stability: 0.78,
      offensiveBonusBias: 0.55,
      coverage: 0.72,
      substitutionValue: 0.60,
      winProbabilityWeight: 0.92,
      robustness: 0.88,
      rosterDepth: 0.72,
      budgetUtilizationTarget: 0.96,
      benchImportance: 0.55,
      captainSafety: 0.72,
    },
  },
  {
    id: "mantra_flex",
    name: "Mantra Flex",
    labelIt: "Mantra flessibile",
    description:
      "Ruleset MANTRA con quote default 12 ruoli; valorizza eligible_roles multipli. Pool ampio (minQtA basso) per massimizzare flessibilità di modulo.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 12,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 10,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.70,
        maxInflationMultiplier: 1.55,
        baseInflationRate: 0.05,
        baselineParticipants: 8,
        teamStrengthMultiplier: 0.12,
      },
      solverTimeoutSeconds: 60,
      maxSinglePlayerBudgetShare: 0.28,
      ruleset: "MANTRA",
      mantraRoleQuotas: {
        Por: 3,
        Dc: 3,
        B: 2,
        Dd: 2,
        Ds: 1,
        E: 1,
        M: 2,
        C: 5,
        T: 1,
        W: 1,
        A: 2,
        Pc: 2,
      },
      preferredFormation: null,
      riskAversion: 0.35,
      varBlend: 0.25,
      esvWeight: 0.20,
      valuationMode: "SEASON_VALUE",
      minStartProbability: null,
      replacementMethod: "percentile",
      strategyNames: ["BALANCED"],
      customStrategies: null,
    },
    policy: {
      risk: 0.45,
      stability: 0.55,
      offensiveBonusBias: 0.50,
      coverage: 0.82,
      substitutionValue: 0.72,
      winProbabilityWeight: 0.55,
      robustness: 0.68,
      rosterDepth: 0.78,
      budgetUtilizationTarget: 0.93,
      benchImportance: 0.68,
      captainSafety: 0.55,
      preferMultiRole: true,
    },
  },

  {
    id: "robust_monte_carlo",
    name: "Robust Monte Carlo",
    labelIt: "Rosa robusta (Monte Carlo)",
    description:
      "SAA a N basso: massimizza stabilità della rosa sotto incertezza ML. riskAversion tenuto basso per evitare doppio conteggio con MC. Ideale prima d'asta quando prediction_std è disponibile.",
    request: {
      budget: 500,
      numParticipants: 8,
      minQtA: 2,
      minDistinctTeams: 10,
      maxPlayersPerTeam: 4,
      bigTeams: DEFAULT_BIG_TEAMS,
      bigTeamsCap: 12,
      formations: DEFAULT_FORMATIONS,
      inflationConfig: {
        inflationPercentileThreshold: 0.7,
        maxInflationMultiplier: 1.35,
        baseInflationRate: 0.04,
        baselineParticipants: 8,
      },
      solverTimeoutSeconds: 45,
      maxSinglePlayerBudgetShare: 0.22,
      riskAversion: 0.15,
      varBlend: 0.15,
      esvWeight: 0.1,
      valuationMode: "PER_MATCH_RATING",
      minStartProbability: 0.35,
      replacementMethod: "percentile",
      strategyNames: null,
      monteCarlo: {
        enabled: true,
        nSimulations: 10,
        mode: "saa_frequency",
        riskLambda: 0.5,
        randomSeed: 42,
      },
      nearOptimal: {
        enabled: true,
        nAlternatives: 3,
        excludeTopM: 2,
        maxScoreDropPct: 0.15,
      },
    },
    policy: {
      risk: 0.25,
      stability: 0.9,
      offensiveBonusBias: 0.35,
      coverage: 0.75,
      substitutionValue: 0.65,
      winProbabilityWeight: 0.7,
      robustness: 0.92,
      rosterDepth: 0.7,
      budgetUtilizationTarget: 0.92,
      benchImportance: 0.55,
      captainSafety: 0.75,
      minStartProbability: 0.35,
      preferBigTeams: false,
      preferMultiRole: true,
      adaptive: false,
    },
  },
] as const;

/** O(1) lookup by preset id. */
export const OPTIMIZER_PRESETS_BY_ID: ReadonlyMap<string, OptimizerPreset> =
  new Map(OPTIMIZER_PRESETS.map(p => [p.id, p]));

export function findOptimizerPreset(id: string): OptimizerPreset | undefined {
  return OPTIMIZER_PRESETS_BY_ID.get(id);
}
