"""End-to-end test for the quotation feature pipeline.

Runs without a database connection: simulates the join by treating the
Fantacalcio id as the FotMob id (a stand-in). The real mapping happens
inside ``ml.data.import_quotations`` when the operator runs the CLI
against the actual PostgreSQL instance.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

# Force UTF-8 output on Windows consoles that default to cp1252.
try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception as exc:
    print(f"UTF-8 console reconfigure skipped (non-critical): {exc}", file=sys.stderr)

# Make the project importable.
sys.path.insert(0, r"c:\Users\L.Brunori\Documents\Progetti\personal\analysis")

from ml.data.import_quotations import (
    discover_season_files,
    load_quotation_dataframe,
    normalise_player_name,
    normalise_team,
)

BASE = Path(r"c:\Users\L.Brunori\Documents\Progetti\personal\analysis\quotazioni")


def section(title: str) -> None:
    print()
    print("=" * 70)
    print(title)
    print("=" * 70)


def main() -> int:
    # ── TEST 1: discovery + load ─────────────────────────────────────────
    section("TEST 1: DISCOVERY + LOAD")
    files = discover_season_files(BASE)
    print(f"Found {len(files)} files:")
    for f in files:
        print(f"  - {f.path.name}  (season_start={f.season_start})")

    frames: list[pd.DataFrame] = []
    for sf in files:
        df = load_quotation_dataframe(sf)
        frames.append(df)
        print(f"  loaded {len(df):>4d} rows from {sf.path.name}")
    combined = pd.concat(frames, ignore_index=True)
    print(
        f"Total: {len(combined)} rows, "
        f"{combined.fantacalcio_id.nunique()} unique Fantacalcio players"
    )

    # ── TEST 2: normalisation ────────────────────────────────────────────
    section("TEST 2: NORMALISATION SAMPLES")
    name_samples = [
        "Dybala  Paulo",
        "Pau López",
        "M'Bala Nzola",
        "Łukasz Skorupski",
        "Darmian",
        "De Sciglio",
    ]
    for n in name_samples:
        print(f"  {n!r:30s}  ->  {normalise_player_name(n)!r}")
    team_samples = [
        "AS Roma",
        "FC Internazionale",
        "Hellas Verona FC",
        "AC Milan",
        "Juventus",
    ]
    for t in team_samples:
        print(f"  {t!r:30s}  ->  {normalise_team(t)!r}")

    # ── TEST 3: feature computation (offline simulation) ────────────────
    section("TEST 3: FEATURE COMPUTATION (offline simulation)")
    sim = combined.rename(columns={"role": "canonical_role"}).copy()
    # Identity join: pretend fantacalcio_id == player_fotmob_id. The real
    # import script does a (name, team, role) match against
    # player_profiles instead.
    sim["player_fotmob_id"] = sim["fantacalcio_id"]
    sim = sim.sort_values(["player_fotmob_id", "season_start"])

    # 1) qt_a_norm (would be generated by the SQL column in production).
    sim["qt_a_norm"] = sim["qt_a"] / 300.0
    sim["qt_i_norm"] = sim["qt_i"] / 300.0

    # Cast to float to avoid Int64 / boolean NA ambiguity in np.where.
    qt_a = pd.to_numeric(sim["qt_a"], errors="coerce").astype(float)
    qt_i = pd.to_numeric(sim["qt_i"], errors="coerce").astype(float)

    # 2) price_delta_pct.
    valid_i = qt_i.gt(0) & qt_a.notna() & qt_i.notna()
    sim["price_delta_pct"] = np.where(
        valid_i.fillna(False),
        (qt_a - qt_i) / qt_i,
        np.nan,
    )
    sim["price_delta_pct"] = sim["price_delta_pct"].clip(-0.8, 2.0)

    # 3) qt_a_vs_role_median (z-score within season×role).
    grp = sim.groupby(["season_start", "canonical_role"])[qt_a.name]
    med = grp.transform("median")
    std = grp.transform("std")
    valid_std = std.gt(0) & qt_a.notna()
    sim["qt_a_vs_role_median"] = np.where(
        valid_std.fillna(False), (qt_a - med) / std, np.nan
    )

    # 4) Lagged qt_a + price_trend_2y.
    g = sim.groupby("player_fotmob_id", sort=False)
    sim["qt_a_lag1"] = pd.to_numeric(g["qt_a"].shift(1), errors="coerce").astype(float)
    valid_lag = sim["qt_a_lag1"].gt(0) & qt_a.notna()
    sim["price_trend_2y"] = np.where(
        valid_lag.fillna(False),
        (qt_a - sim["qt_a_lag1"]) / sim["qt_a_lag1"],
        np.nan,
    )
    sim["price_trend_2y"] = sim["price_trend_2y"].clip(-0.8, 2.0)

    # Coverage report.
    n = len(sim)
    for col in (
        "qt_a_norm",
        "price_delta_pct",
        "qt_a_vs_role_median",
        "price_trend_2y",
    ):
        nn = int(sim[col].notna().sum())
        print(f"  {col:25s}  {nn:5d} / {n}  ({100.0 * nn / n:.1f}%)")

    # ── TEST 4: value ranges ─────────────────────────────────────────────
    section("TEST 4: VALUE RANGES")
    for col in (
        "qt_a_norm",
        "price_delta_pct",
        "qt_a_vs_role_median",
        "price_trend_2y",
    ):
        s = sim[col]
        print(
            f"  {col:25s}  min={s.min():>7.4f}  "
            f"max={s.max():>7.4f}  mean={s.mean():>7.4f}  std={s.std():>7.4f}"
        )

    # ── TEST 5: Acerbi (player present in all 3 seasons) ────────────────
    section("TEST 5: EXAMPLE — Acerbi (present in all 3 seasons)")
    acerbi = sim[sim["name"] == "Acerbi"].sort_values("season_start")
    if acerbi.empty:
        print("  Acerbi not found in this dataset (only GK/D or transfers).")
    else:
        cols = [
            "season_start",
            "team",
            "qt_a",
            "qt_i",
            "qt_a_norm",
            "price_delta_pct",
            "price_trend_2y",
        ]
        print(acerbi[cols].to_string(index=False))

    # ── TEST 6: top momentum ─────────────────────────────────────────────
    section("TEST 6: Top 5 by price_delta_pct (momentum, season 2024/25)")
    mom = sim[sim["season_start"] == 2024].nlargest(5, "price_delta_pct")
    print(
        mom[["name", "team", "qt_a", "qt_i", "price_delta_pct"]].to_string(index=False)
    )

    # ── TEST 7: top z-score ──────────────────────────────────────────────
    section("TEST 7: Top 5 FWD by qt_a_vs_role_median (season 2024/25)")
    top = sim[
        (sim["season_start"] == 2024) & (sim["canonical_role"] == "FWD")
    ].nlargest(5, "qt_a_vs_role_median")
    print(top[["name", "team", "qt_a", "qt_a_vs_role_median"]].to_string(index=False))

    # ── TEST 8: edge cases (qt_i = 0) ────────────────────────────────────
    section("TEST 8: EDGE CASES — qt_i = 0 (rookies)")
    zero_qti = sim[sim["qt_i"] == 0]
    print(f"  Rows with qt_i == 0: {len(zero_qti)}")
    if not zero_qti.empty:
        print(
            zero_qti[["name", "qt_a", "qt_i", "price_delta_pct"]]
            .head(5)
            .to_string(index=False)
        )

    print()
    print("All tests passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
